"""empty message

Revision ID: 06605e17f0b4
Revises: 
Create Date: 2019-03-26 10:44:23.971622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06605e17f0b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'name')
    # ### end Alembic commands ###
