restaurants_data = [
    {
        "name": "The London Grill",
        "desc": "Modern British grill serving steaks, roasts, and seasonal dishes.",
        "address": "221B Baker Street, London",
        "phone": "+44 20 7946 0991",
        "email": "info@thelondongrill.co.uk",
        "cuisine": "British",
        "review_count": 240,
        "reviews_average": 1.5,
        "logo": "logos/london_grill.png"
    },
    {
        "name": "Camden Tacos",
        "desc": "Mexican street food with fresh tacos, burritos, and margaritas.",
        "address": "45 Camden High Street, London",
        "phone": "+44 20 7123 3344",
        "email": "hello@camdentacos.co.uk",
        "cuisine": "Mexican",
        "review_count": 180,
        "reviews_average": 2.3,
        "logo": "logos/camden_tacos.png"
    },
    {
        "name": "Sushi Soho",
        "desc": "Japanese dining with sushi, sashimi and creative rolls.",
        "address": "12 Dean Street, Soho, London",
        "phone": "+44 20 7555 9988",
        "email": "contact@sushisoho.co.uk",
        "cuisine": "Japanese",
        "review_count": 320,
        "reviews_average": 3.7,
        "logo": "logos/sushi_soho.png"
    },
    {
        "name": "Pasta Piccadilly",
        "desc": "Italian trattoria serving fresh pasta and pizzas.",
        "address": "100 Piccadilly, London",
        "phone": "+44 20 7333 2233",
        "email": "reservations@pastapiccadilly.co.uk",
        "cuisine": "Italian",
        "review_count": 275,
        "reviews_average": 0.4,
        "logo": "logos/pasta_piccadilly.png"
    },
    {
        "name": "Shoreditch Burgers",
        "desc": "Craft burgers with locally sourced ingredients.",
        "address": "88 Shoreditch High Street, London",
        "phone": "+44 20 7999 4455",
        "email": "info@shoreditchburgers.co.uk",
        "cuisine": "American",
        "review_count": 310,
        "reviews_average": 4.6,
        "logo": "logos/shoreditch_burgers.png"
    },
    {
        "name": "The Curry House",
        "desc": "Authentic Indian curries with traditional spices.",
        "address": "77 Brick Lane, London",
        "phone": "+44 20 7333 9988",
        "email": "hello@thecurryhouse.co.uk",
        "cuisine": "Indian",
        "review_count": 190,
        "reviews_average": 3.2,
        "logo": "logos/curry_house.png"
    },
    {
        "name": "Dragon Palace",
        "desc": "Chinese restaurant with dim sum and Cantonese specialties.",
        "address": "9 Gerrard Street, Chinatown, London",
        "phone": "+44 20 7222 1199",
        "email": "reservations@dragonpalace.co.uk",
        "cuisine": "Chinese",
        "review_count": 280,
        "reviews_average": 2.5,
        "logo": "logos/dragon_palace.png"
    },
    {
        "name": "Tapas Covent Garden",
        "desc": "Spanish tapas and sangria in a cozy setting.",
        "address": "14 Floral Street, Covent Garden, London",
        "phone": "+44 20 7555 6677",
        "email": "info@tapascg.co.uk",
        "cuisine": "Spanish",
        "review_count": 150,
        "reviews_average": 3.1,
        "logo": "logos/tapas_covent_garden.png"
    },
    {
        "name": "Vegan Vibes",
        "desc": "Plant-based cuisine with a focus on sustainability.",
        "address": "33 Green Lane, London",
        "phone": "+44 20 7999 2233",
        "email": "hello@veganvibes.co.uk",
        "cuisine": "Vegan",
        "review_count": 220,
        "reviews_average": 2.6,
        "logo": "logos/vegan_vibes.png"
    },
    {
        "name": "Thames Seafood",
        "desc": "Fresh fish and seafood with views of the Thames.",
        "address": "50 Riverside Walk, London",
        "phone": "+44 20 7888 3344",
        "email": "contact@thamesseafood.co.uk",
        "cuisine": "Seafood",
        "review_count": 260,
        "reviews_average": 1.4,
        "logo": "logos/thames_seafood.png"
    },
    {
        "name": "Le Petit Paris",
        "desc": "French bistro with croissants, quiche and fine wines.",
        "address": "22 Kensington High Street, London",
        "phone": "+44 20 7555 7788",
        "email": "info@lepetitparis.co.uk",
        "cuisine": "French",
        "review_count": 130,
        "reviews_average": 3.2,
        "logo": "logos/le_petit_paris.png"
    },
    {
        "name": "Pizza Napoli London",
        "desc": "Neapolitan-style pizza baked in a wood-fired oven.",
        "address": "66 Oxford Street, London",
        "phone": "+44 20 7444 5566",
        "email": "reservations@pizzanapolilondon.co.uk",
        "cuisine": "Italian",
        "review_count": 240,
        "reviews_average": 2.5,
        "logo": "logos/pizza_napoli.png"
    },
    {
        "name": "Grill & Ale",
        "desc": "Steaks and BBQ served with local craft ales.",
        "address": "12 King’s Road, London",
        "phone": "+44 20 7555 8899",
        "email": "contact@grillandale.co.uk",
        "cuisine": "BBQ",
        "review_count": 210,
        "reviews_average": 1.3,
        "logo": "logos/grill_ale.png"
    },
    {
        "name": "Mediterranean Table",
        "desc": "Healthy Mediterranean dishes with olive oil and fresh herbs.",
        "address": "19 Notting Hill Gate, London",
        "phone": "+44 20 7666 7788",
        "email": "info@medtable.co.uk",
        "cuisine": "Mediterranean",
        "review_count": 185,
        "reviews_average": 4.4,
        "logo": "logos/mediterranean_table.png"
    },
    {
        "name": "The Ramen Bar",
        "desc": "Japanese ramen made from scratch daily.",
        "address": "8 Tottenham Court Road, London",
        "phone": "+44 20 7555 4433",
        "email": "hello@theramenbar.co.uk",
        "cuisine": "Japanese",
        "review_count": 310,
        "reviews_average": 2.7,
        "logo": "logos/ramen_bar.png"
    },
    {
        "name": "Morning Glory Café",
        "desc": "Breakfast and brunch café with fresh juices.",
        "address": "3 Portobello Road, London",
        "phone": "+44 20 7999 5566",
        "email": "contact@morningglory.co.uk",
        "cuisine": "Breakfast",
        "review_count": 170,
        "reviews_average": 3.3,
        "logo": "logos/morning_glory.png"
    },
    {
        "name": "Prime Steakhouse",
        "desc": "Premium cuts of beef cooked to order.",
        "address": "28 Bishopsgate, London",
        "phone": "+44 20 7888 1122",
        "email": "reservations@primestep.co.uk",
        "cuisine": "Steakhouse",
        "review_count": 260,
        "reviews_average": 0.6,
        "logo": "logos/prime_steakhouse.png"
    },
    {
        "name": "Bangkok Spice",
        "desc": "Authentic Thai food with street-style flavors.",
        "address": "55 Charing Cross Road, London",
        "phone": "+44 20 7444 7788",
        "email": "info@bangkokspice.co.uk",
        "cuisine": "Thai",
        "review_count": 200,
        "reviews_average": 3.5,
        "logo": "logos/bangkok_spice.png"
    },
    {
        "name": "The Craft Taproom",
        "desc": "Pub with rotating craft beers and bar snacks.",
        "address": "42 Borough High Street, London",
        "phone": "+44 20 7333 4455",
        "email": "hello@crafttaproom.co.uk",
        "cuisine": "Pub",
        "review_count": 225,
        "reviews_average": 4.4,
        "logo": "logos/craft_taproom.png"
    },
    {
        "name": "Sweet Bliss",
        "desc": "Dessert café serving cakes, gelato and milkshakes.",
        "address": "10 Oxford Circus, London",
        "phone": "+44 20 7666 3344",
        "email": "contact@sweetbliss.co.uk",
        "cuisine": "Dessert",
        "review_count": 140,
        "reviews_average": 3.2,
        "logo": "logos/sweet_bliss.png"
    },
    {
        "name": "Urban Tacos London",
        "desc": "Street-style tacos with a London twist.",
        "address": "31 Liverpool Street, London",
        "phone": "+44 20 7555 6677",
        "email": "info@urbantacoslondon.co.uk",
        "cuisine": "Mexican",
        "review_count": 270,
        "reviews_average": 3.6,
        "logo": "logos/urban_tacos.png"
    },
    {
        "name": "Golden Lotus",
        "desc": "Upscale Chinese fine dining in London Chinatown.",
        "address": "88 Gerrard Street, London",
        "phone": "+44 20 7222 3344",
        "email": "reservations@goldenlotus.co.uk",
        "cuisine": "Chinese",
        "review_count": 240,
        "reviews_average": 2.5,
        "logo": "logos/golden_lotus.png"
    },
    {
        "name": "Brick Lane Bagels",
        "desc": "Famous London bagels with salt beef and cream cheese.",
        "address": "152 Brick Lane, London",
        "phone": "+44 20 7999 7788",
        "email": "hello@bricklanebagels.co.uk",
        "cuisine": "Deli",
        "review_count": 310,
        "reviews_average": 4.7,
        "logo": "logos/bricklane_bagels.png"
    },
    {
        "name": "Soho Tapas",
        "desc": "Trendy tapas bar with live music nights.",
        "address": "19 Frith Street, Soho, London",
        "phone": "+44 20 7555 2233",
        "email": "info@sohotapas.co.uk",
        "cuisine": "Spanish",
        "review_count": 190,
        "reviews_average": 4.3,
        "logo": "logos/soho_tapas.png"
    },
    {
        "name": "Garden Bowl",
        "desc": "Healthy bowls, smoothies and vegan options.",
        "address": "5 Covent Garden, London",
        "phone": "+44 20 7333 6677",
        "email": "hello@gardenbowl.co.uk",
        "cuisine": "Healthy",
        "review_count": 160,
        "reviews_average": 4.4,
        "logo": "logos/garden_bowl.png"
    },
    {
        "name": "Smokehouse London",
        "desc": "BBQ smokehouse with brisket, ribs and pulled pork.",
        "address": "72 Kingsland Road, London",
        "phone": "+44 20 7444 2211",
        "email": "contact@smokehouselondon.co.uk",
        "cuisine": "BBQ",
        "review_count": 280,
        "reviews_average": 4.6,
        "logo": "logos/smokehouse_london.png"
    },
    {
        "name": "Spice Route London",
        "desc": "Fusion cuisine inspired by the ancient spice trade.",
        "address": "11 Southbank, London",
        "phone": "+44 20 7888 5566",
        "email": "info@spiceroutelondon.co.uk",
        "cuisine": "Fusion",
        "review_count": 200,
        "reviews_average": 4.5,
        "logo": "logos/spice_route.png"
    }
]